# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=django22-py35
    - python: 3.6
      env: TOXENV=django22-py36
    - python: 3.6
      env: TOXENV=django30-py36
    - python: 3.7
      env: TOXENV=django22-py37
    - python: 3.7
      env: TOXENV=django30-py37
    - python: 3.8
      env: TOXENV=django228-py38
    - python: 3.8
      env: TOXENV=django30-py38


before_install:
  - python -m pip install codecov tox

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python -m pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov
